version: "3.8"

services:
  postgresql:
    image: postgres:16-alpine
    restart: always
    container_name: postgres-vegastar
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=vegastar"
    ports:
      - 15433:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
    postgresdata: